export const COLLECTIONS = {
  BOOKINGS: 'bookings',
  SERVICES: 'services',
  BARBERS: 'barbers',
  REVIEWS: 'reviews',
  GALLERY: 'gallery',
  SETTINGS: 'settings',
  ADMINS: 'admins',
  OFFERS: 'offers',
  BANNERS: 'banners',
  WAITLIST: 'waitlist',
  DAILY_NOTES: 'dailyNotes',
  NOTIFICATIONS: 'notifications',
  NOTIFICATION_TEMPLATES: 'notificationTemplates',
  ACTIVITY_LOGS: 'activityLogs',
  AI_CACHE: 'aiCache',
  AI_PROMPTS: 'aiPrompts',
  AI_LOGS: 'aiLogs',
} as const;
